[theme]
# Primary accent color for interactive elements.
primaryColor = "#ff0000"

# Background color for the main content area.
backgroundColor =  "#006400"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#ffffff"

# Font family for all text in the app, except code blocks. One of "sans serif", "sans" or
# Default: "sans"
font = "sans serif"